### ISSUE TITLE
Snap.net unhandled exception. Unable to start the app.

### ISSUE THREAD

**Issue by almostserious** [stijnvdb88/Snap.Net#37]
Recently, I am getting these errors when I am trying to start snap.net.
A uninstall and reinstall doesn't help.
It happened over night, the only change in the System might be some windows updates.
Maybe the logs are helpful below:

Source: Application Error:
```
Faulting application name: Snap.Net.exe, version: 0.26.0.2, time stamp: 0xdb293692
Faulting module name: KERNELBASE.dll, version: 10.0.22000.434, time stamp: 0x78dc11b6
Exception code: 0xe0434352
Fault offset: 0x0013ec52
Faulting process ID: 0x2314
Faulting application start time: 0x01d81d11708d11a7
Faulting application path: C:\Program Files\Snap.Net\Snap.Net.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 51c42251-1520-4e35-8aa1-c7a03ac20008
Faulting package full name: 
Faulting package-relative application ID: 

```
Source: .NET Runtime
```
Application: Snap.Net.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.Configuration..ctor(System.String, System.Type, System.Object[])
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(System.Configuration.ConfigurationFileMap, Boolean, System.Configuration.ConfigurationUserLevel, System.String)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(System.Configuration.ConfigurationFileMap, Boolean, System.Configuration.ConfigurationUserLevel, System.String, Boolean)
   at System.Configuration.ClientSettingsStore.ReadSettingsFromFile(System.String, System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(System.String, System.String, Boolean, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection, Boolean)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at SnapDotNet.SnapSettings.Init()
   at SnapDotNet.Snapcast.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at SnapDotNet.SingleInstanceManager.OnStartup(Microsoft.VisualBasic.ApplicationServices.StartupEventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[])
   at SnapDotNet.EntryPoint.Main(System.String[])

```

**Comment by stijnvdb88** [comment]
Hi, thanks for the logs - very helpful! This looks like your config file got corrupted, I've seen that before unfortunately.
Could you paste here the contents of the `user.config` file here as well please? You'll find it in `C:\Users\<User>\AppData\Local\SnapDotNet\Snap.Net.Exe_Url_<CatJumpedOnSomeonesKeyboard>\0.26.0.3`. 

My guess is that file will either be incomplete, or have gibberish in it (got corrupted mid-write somehow). Renaming/deleting this file will fix the crash for you. But please still paste its contents here as well, I'd like to try and get to the bottom of this issue.

Thanks!

**Comment by almostserious** [comment]
Indeed it seems like the file was corrupted. It has a lot of NUL Values in them.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <SnapDotNet.Properties.Settings>
            <setting name="Server" serializeAs="String">
                <value>192.168.1.100</value>
            </setting>
            <setting name="ControlPort" serializeAs="String">
                <value>1705</value>
            </setting>
            <setting name="PlayDevices" serializeAs="String">
                <value />
            </setting>
            <setting name="PlayerPort" serializeAs="String">
                <value>1704</value>
                                                                                                                                      
```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
[user.zip](https://github.com/stijnvdb88/Snap.Net/files/8043422/user.zip)
