### ISSUE TITLE
Clicking tray icon while broadcasting causes app crashes

### ISSUE THREAD

**Issue by baddwin** [stijnvdb88/Snap.Net#40]
Snap.Net version : 0.26.0.2
OS: Windows 11

It's similar to #39 , but with additional state, that is occured while broadcasting, and using virtual sound card.

Here's the log from Event Viewer:

```
Log Name:      Application
Source:        .NET Runtime
Date:          20/05/2022 15.11.35
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      AMZ-Desktop
Description:
Application: Snap.Net.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at SnapDotNet.SnapControl.Group.<_OnStreamPropertiesUpdated>b__9_0()
   at System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action)
   at SnapDotNet.SnapControl.Group._OnStreamPropertiesUpdated()
   at SnapDotNet.SnapControl.Group._OnGroupUpdated()
   at SnapDotNet.SnapControl.Group..ctor(SnapDotNet.ControlClient.SnapcastClient, SnapDotNet.ControlClient.JsonRpcData.Group)
   at SnapDotNet.SnapControl.SnapControl._OnServerUpdated()
   at SnapDotNet.SnapControl.SnapControl..ctor(Hardcodet.Wpf.TaskbarNotification.Interop.Point, SnapDotNet.ControlClient.SnapcastClient)
   at SnapDotNet.Snapcast.ShowSnapPane(Boolean)
   at SnapDotNet.NotifyIconViewModel+<>c.<get_ShowBalloonCommand>b__9_1()
   at SnapDotNet.DelegateCommand.Execute(System.Object)
   at Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(System.Windows.Input.ICommand, System.Object, System.Windows.IInputElement)
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon+<>c__DisplayClasse.<OnMouseEvent>b__8()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Windows.Threading.DispatcherOperation.Wait(System.TimeSpan)
   at System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherOperation, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action)
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.DoSingleClickAction(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32)

```

**Comment by stijnvdb88** [comment]
Hi! apologies for taking so long - I just released Snap.Net [v0.260.3](https://github.com/stijnvdb88/Snap.Net/releases/tag/v0.26.0.3) which has a potential fix for this crash. Please try it and let me know if it worked

**Comment by baddwin** [comment]
Hi @stijnvdb88, I got it fixed in my end, thank you! So I close this issue.
