### ISSUE TITLE
Snap.Net crashes when attempt to open the UI

### ISSUE THREAD

**Issue by cruiser-rtd** [stijnvdb88/Snap.Net#45]
Hi,

Love the client, but am having issues after rebuilding SnapServer host on a Raspberry with "all the latest" updates on the Raspberry.

My Windows Clients (all windows 10) that were working fine before now have an issue if I try to open the main UI of Snap.Net.  When I click the icon in my try, the app crashes with this error in Event log

Application: Snap.Net.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at SnapDotNet.SnapControl.Group.<_OnStreamPropertiesUpdated>b__9_0()
   at System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action)
   at SnapDotNet.SnapControl.Group._OnStreamPropertiesUpdated()
   at SnapDotNet.SnapControl.Group._OnGroupUpdated()
   at SnapDotNet.SnapControl.Group..ctor(SnapDotNet.ControlClient.SnapcastClient, SnapDotNet.ControlClient.JsonRpcData.Group)
   at SnapDotNet.SnapControl.SnapControl._OnServerUpdated()
   at SnapDotNet.SnapControl.SnapControl..ctor(Hardcodet.Wpf.TaskbarNotification.Interop.Point, SnapDotNet.ControlClient.SnapcastClient)
   at SnapDotNet.Snapcast.ShowSnapPane(Boolean)
   at SnapDotNet.NotifyIconViewModel+<>c.<get_ShowBalloonCommand>b__9_1()
   at SnapDotNet.DelegateCommand.Execute(System.Object)
   at Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(System.Windows.Input.ICommand, System.Object, System.Windows.IInputElement)
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon+<>c__DisplayClasse.<OnMouseEvent>b__8()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Windows.Threading.DispatcherOperation.Wait(System.TimeSpan)
   at System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherOperation, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action)
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.DoSingleClickAction(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32)

It does play the stream just fine, and will even Broadcast.  I just can't open the UI to then groups and devices!

I can open all of the other right-click screens just fine (Settings..., Player, Broadcast).

I have other Mopidy/Snapcast clients and all are fine.  It is only the Snap.Net client on Windows that is having an issue.

Thanks for investigating this.

**Comment by cruiser-rtd** [comment]
This is similar to #40 , same error log.  However, I've disabled Broadcasting so that isolates the problem to just the client UI I'd believe.

**Comment by stijnvdb88** [comment]
Hi! I just released Snap.Net [v0.260.3](https://github.com/stijnvdb88/Snap.Net/releases/tag/v0.26.0.3) which has a potential fix for this crash. Please try it and let me know if it worked

**Comment by cruiser-rtd** [comment]
Working perfectly!  Thank you :)
